### ISSUE TITLE
No module named ioHub

### ISSUE THREAD

**Issue by lopsided** [isolver/ioHub#22]
I am fairly new to python and all the other modules Ive used all tend to have the setup.py file to install it automatically. I have installed all the deps as far as I can tell, but every file or example I run gives this error. Ive added the ioHub path to PYTHONPATH too. I cant find a file called ioHub in the repo so Im a bit confused...

Sorry if this is a dumb question

**Comment by isolver** [comment]
Hi there,

Here are full manual install instructions for the latest master branch code
of ioHub. I have not created a setup.py install script, so basically you
just copy the source folder to your site-packages directory and ensure the
folder is renamed to just ioHub from ioHub-master as it is named in the
github zip download.

Thanks very much,

Sol

## Manually Installing ioHub

The following software must be installed on the computer before proceeding
with the ioHub dependency installation list and installation of ioHub
itself:
1. Python 2.6.8 or 2.7.3 32 bit is required as the Python interpreter. The 32 bit version of Python can be installed on a supported 64 bit OS.
2. Psychopy 1.74.03 or higher and all of it’s dependencies. See the PsychoPy installation http://www.psychopy.org/installation.html page for details.
3. For the NumPy package, please ensure 1.6.2 or greater is installed.

## ioHub Dependency List Installation

Once Python and PsychoPy are installed, the following extra Python packages
must be installed for the ioHub:

### Python 2.7 Package List
1. psutil:http://code.google.com/p/psutil/downloads/detail?name=psutil-0.6.1.win32-py2.7.exe A cross-platform process and system utilities module for Python
2. ujson:http://pypi.python.org/packages/2.7/u/ujson/ujson-1.19.win32-py2.7.exe#md5=a5eda15e99f6091e9e550887b35e7fd4 Ultra fast JSON encoder and decoder for Python
3. msgpack:http://pypi.python.org/packages/2.7/m/msgpack-python/msgpack_python-0.2.0-py2.7-win32.egg#md5=d52bd856ca8c8d9a6ee86937e1b4c644 It’s like JSON. but fast and small.
4. gevent:https://github.com/downloads/SiteSupport/gevent/gevent-1.0rc2.win32-py2.7.exe A coroutine-based Python networking library that uses greenlet to provide a high-level synchronous API on top of the libevent event loop.
5. greenlet:http://pypi.python.org/packages/2.7/g/greenlet/greenlet-0.4.0.win32-py2.7.exe#md5=910896116b1e4fd527b8afaadc7132f3 The  greenlet package is a spin-off of Stackless, a version of CPython that supports micro-threads called “tasklets”.
6. pytables: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pytables PyTables is a package for managing hierarchical datasets and designed to efficiently and easily cope with extremely large amounts of data.
7. numexpr:http://code.google.com/p/numexpr/downloads/detail?name=numexpr-1.4.2.win32-py2.7.exe&can=2&q= Fast numerical array expression evaluator for Python and NumPy.
8. pyYAML:http://pyyaml.org/download/pyyaml/PyYAML-3.10.win32-py2.7.exe PyYAML is a YAML parser and emitter for Python.
9. pywin32:http://sourceforge.net/projects/pywin32/files/pywin32/Build%20217/pywin32-217.win32-py2.7.exe/download Python Extensions for Windows
10. pyHook:http://sourceforge.net/projects/pyhook/files/pyhook/1.5.1/pyHook-1.5.1.win32-py2.7.exe/download Python wrapper for global input hooks in Windows.

### Python 2.6 Package List
1. psutil:https://code.google.com/p/psutil/downloads/detail?name=psutil-0.6.1.win32-py2.6.exe A cross-platform process and system utilities module for Python
2. ujson:https://pypi.python.org/packages/2.6/u/ujson/ujson-1.30.win32-py2.6.exe Ultra fast JSON encoder and decoder for Python
3. msgpack: http://www.lfd.uci.edu/~gohlke/pythonlibs/#msgpack It’s like JSON. but fast and small.
4. greenlet:https://pypi.python.org/packages/2.6/g/greenlet/greenlet-0.4.0.win32-py2.6.exe The greenlet package is a spin-off of Stackless, a version of CPython that supports micro-threads called “tasklets”.
5. gevent:https://code.google.com/p/gevent/downloads/detail?name=gevent-1.0b4.win32-py2.6.exe&can=2&q=
   A coroutine-based Python networking library that uses greenlet to provide a high-level synchronous API on top of the libevent event loop.
6. numexpr:http://code.google.com/p/numexpr/downloads/detail?name=numexpr-1.4.2.win32-py2.6.exe&can=2&q=
   Fast numerical array expression evaluator for Python and NumPy.
7. pytables: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pytables PyTables is a package for managing hierarchical datasets and designed to efficiently and easily cope with extremely large amounts of data.
8. pyYAML:http://pyyaml.org/download/pyyaml/PyYAML-3.10.win32-py2.6.exe PyYAML is a YAML parser and emitter for Python.
9. pyHook:http://sourceforge.net/projects/pyhook/files/pyhook/1.5.1/pyHook-1.5.1.win32-py2.6.exe/download
   Python wrapper for global input hooks in Windows.
10. pywin32:http://sourceforge.net/projects/pywin32/files/pywin32/Build%20217/pywin32-217.win32-py2.6.exe/download Python Extensions for Windows
11. OrderedDict : https://pypi.python.org/pypi/ordereddict An API compatible version of the collections.OrderedDict class that was added to the Python 2.7 release. This external package works with Python 2.6.

Several of the devices supported by ioHub require the installation of an OS
driver for the device that can not be included with the ioHub package due
to licensing considerations. Please refer to the documentation page for
each device to ensure that any device specific driver required is known
about and is installed.

## ioHub Package Installation

To install the ioHub package itself, currently no python package installer
exists. Therefore the ioHub source is simply copied to your Python
site-packages folder, putting the ioHub directory in the site-packages
directory of your Python installation. To do so:
1. Get a zip download https://github.com/isolver/ioHub/zipball/master/ of the ioHub project source https://www.github.com/isolver/ioHub/
2. Open the zip file.
3. Copy the folder in the zip file to your python site-packages directory. (likely something like C:\Python27\Lib\site-packages, or C:\Python27\Lib\site-packages)
4. Rename the folder you copied to the site-packages directory from ioHub-master to just ioHub .
