### ISSUE TITLE
ioHub should use the PsychoPy logging framework

### ISSUE THREAD

**Issue by isolver** [isolver/ioHub#61]
This makes a lot of sense from an integration point of view. Only thing that will have to be considered is how to make the pscyhopy log framework multiprocess safe, so > 1 process can be sending log events to be saved without the log messages getting intermixed.

**Comment by garyfeng** [comment]
Sol -- the HDF5 data logging works well for our projects, which do not use psychopy functions. Just wanted to make sure iohub continues to support that. I would prefer not to depend on another framework that is not absolutely necessary. 

Thanks,
- gary

**Comment by isolver** [comment]
The HDF5 based file structure that the ioDataStore uses will definitely not change. Before using pytables / HDF5 I only dreamed of being able to save 1000Hz sample data in real time and not have it effect the experiment timing. ;)

The PsychoPy logging is a different thing all together. The idea is it could be used for writing status and debugging msg's etc from the ioHub process, so we can get away from the stdout based message / error printing that is 'overly' used right now in the project. 

A person could use the PsychoPy logging for what ever they like BTW when it is integrated; above I refer to why doing this would be a + from my own POV. ;)

**Comment by isolver** [comment]
Fixed. Total functional backwards compatibility for ioHub, but now is relatively well integrated with the psychopy logging module capabilities.
